# -*- coding: utf-8 -*-
"""RAGMLB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USJMfN63MO810VF8NV_Ynm7inzWbdTri
"""

from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
from langchain.document_loaders import TextLoader
from langchain.indexes import VectorstoreIndexCreator
import os

os.environ["OPENAI_API_KEY"] = "the API keys were not working "

loader = TextLoader("sample_document.txt")

index = VectorstoreIndexCreator().from_loaders([loader])

qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=index.vectorstore.as_retriever())

query = "What is the main topic of the document?"
response = qa.run(query)
print(response)